Normal form game is created by passing two matrices into nash.Game()function

In [1]:
import numpy as np 
import nashpy as nash
A=np.array([[1,-1],[-1,1]])
result=nash.Game(A)
print(result)

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]


Calculate utilities

In [2]:
A=np.array([[3,0],[5,1]])
B=np.array([[3,5],[0,1]])
sol=nash.Game(A,B)
print(sol)

Bi matrix game with payoff matrices:

Row player:
[[3 0]
 [5 1]]

Column player:
[[3 5]
 [0 1]]


So for every player we have two strategies

In [3]:
# case 1: if Row player use the first strategy and the column player use the second
strategy_row=np.array([1,0])
strategy_column=np.array([0,1])
sol[strategy_row,strategy_column]
print(sol[strategy_row,strategy_column])

[0 5]


In [4]:
# in case of incertitude 
strategy_row=np.array([1/3,2/3])
strategy_column=np.array([1,0])
sol[strategy_row,strategy_column]
print(sol[strategy_row,strategy_column])

[4.33333333 1.        ]


Cheking which one is the best strategy 

In [5]:
A=np.array([[1,2],[3,5]])
B=np.array([[3,5],[5,7]])
sol=nash.Game(A,B)
st_r=np.array([1,0])
st_c=np.array([1,0])
print(sol[st_r,st_c])
print(sol.is_best_response(st_r,st_c))

[1 3]
(False, False)


Support enumeration

In [6]:
equilibria=sol.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([0., 1.]))


Interpretation
row player has not to play with the first strategy anymore hes has to use the second strategy
Same think for column player

Fictitious game

In [7]:
A = np.array([[3, 1], [0, 2]])
B = np.array([[2, 0], [1, 3]])
game=nash.Game(A,B)

In [12]:
np.random.seed(0)
iterations=500
play_counts=game.fictitious_play(iterations=iterations)
for rpc,cpc in play_counts:
    print(rpc,cpc)

[0 0] [0 0]
[1. 0.] [0. 1.]
[1. 1.] [1. 1.]
[2. 1.] [1. 2.]
[3. 1.] [2. 2.]
[4. 1.] [3. 2.]
[5. 1.] [4. 2.]
[6. 1.] [5. 2.]
[7. 1.] [6. 2.]
[8. 1.] [7. 2.]
[9. 1.] [8. 2.]
[10.  1.] [9. 2.]
[11.  1.] [10.  2.]
[12.  1.] [11.  2.]
[13.  1.] [12.  2.]
[14.  1.] [13.  2.]
[15.  1.] [14.  2.]
[16.  1.] [15.  2.]
[17.  1.] [16.  2.]
[18.  1.] [17.  2.]
[19.  1.] [18.  2.]
[20.  1.] [19.  2.]
[21.  1.] [20.  2.]
[22.  1.] [21.  2.]
[23.  1.] [22.  2.]
[24.  1.] [23.  2.]
[25.  1.] [24.  2.]
[26.  1.] [25.  2.]
[27.  1.] [26.  2.]
[28.  1.] [27.  2.]
[29.  1.] [28.  2.]
[30.  1.] [29.  2.]
[31.  1.] [30.  2.]
[32.  1.] [31.  2.]
[33.  1.] [32.  2.]
[34.  1.] [33.  2.]
[35.  1.] [34.  2.]
[36.  1.] [35.  2.]
[37.  1.] [36.  2.]
[38.  1.] [37.  2.]
[39.  1.] [38.  2.]
[40.  1.] [39.  2.]
[41.  1.] [40.  2.]
[42.  1.] [41.  2.]
[43.  1.] [42.  2.]
[44.  1.] [43.  2.]
[45.  1.] [44.  2.]
[46.  1.] [45.  2.]
[47.  1.] [46.  2.]
[48.  1.] [47.  2.]
[49.  1.] [48.  2.]
[50.  1.] [49.  2.]
[51.  1.] 