Game theory:
 Is the study of strategic interactions between rational agents

In [2]:
#Creating a game
import nashpy as nash
import numpy as np
A= np.array([[0 ,-1,1],[1,0,-1],[-1,1,0]])
rps=nash.Game(A)
print(rps)

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]


In [3]:
# Another method is
B=-A
rps2=nash.Game(A,B)
print(rps2)

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]


If Row Player use the third strategy 
and the column player use the the second stretegy . 
We can use the modelisation with vectors


In [4]:
sigma_r=[0,0,1]
sigma_c=[0,1,0]
print(rps[sigma_r,sigma_c])

[ 1 -1]


In [5]:
sigma_c=[1/2,1/2,0]
print(rps[sigma_r,sigma_c])

[0. 0.]
